# Copyright 2023-2024 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: slurm
version: 23.11.7
summary: "Slurm: A Highly Scalable Workload Manager"
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster
  management and job scheduling system for large and small Linux clusters.
license: Apache-2.0
website: "https://slurm.schedmd.com"

base: core22
confinement: classic
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x
package-repositories:
  - type: apt
    ppa: ubuntu-hpc/rocm-smi-lib
environment:
  # Need this PATH declaration so that the Python-based
  # snap hooks can find the embedded Python interpreter with
  # the necessary dependencies packaged in `site-packages`.
  # yamllint disable-line rule:line-length
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH

system-usernames:
  snap_daemon: shared

apps:
  logrotate:
    command: usr/sbin/logrotate $SNAP_COMMON/etc/logrotate/logrotate.conf
    daemon: oneshot
    timer: 00:00  # Run `logrotate` once everyday at midnight.

  munged:
    command: sbin/munged.wrapper
    daemon: simple

  munge:
    command: bin/munge --socket $SNAP_COMMON/run/munge/munged.socket.2
  unmunge:
    command: bin/unmunge --socket $SNAP_COMMON/run/munge/munged.socket.2
  remunge:
    command: bin/remunge --socket $SNAP_COMMON/run/munge/munged.socket.2
  mungekey:
    command: sbin/mungekey
  mungectl:
    command: bin/mungectl

  slurmctld:
    command: sbin/slurmctld.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmd:
    command: sbin/slurmd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmdbd:
    command: sbin/slurmdbd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmrestd:
    command: sbin/slurmrestd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurm-prometheus-exporter:
    # yamllint disable-line rule:line-length
    command: bin/prometheus-slurm-exporter -slurm.cli-fallback -slurm.collect-diags
    daemon: simple
    install-mode: disable
    after: [munged]
    restart-condition: always
    restart-delay: 15s

  sacct:
    command: bin/sacct
  sacctmgr:
    command: bin/sacctmgr
  salloc:
    command: bin/salloc
  sattach:
    command: bin/sattach
  sbatch:
    command: bin/sbatch
  sbcast:
    command: bin/sbcast
  scancel:
    command: bin/scancel
  scontrol:
    command: bin/scontrol
  scrontab:
    command: bin/scrontab
  scrun:
    command: bin/scrun
  sdiag:
    command: bin/sdiag
  sh5util:
    command: bin/sh5util
  sinfo:
    command: bin/sinfo
  sprio:
    command: bin/sprio
  squeue:
    command: bin/squeue
  sreport:
    command: bin/sreport
  srun:
    command: bin/srun
  sshare:
    command: bin/sshare
  sstat:
    command: bin/sstat
  strigger:
    command: bin/strigger
  sview:
    command: bin/sview

parts:
  patch:
    source: patches/
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*

  overlay:
    source: overlays/
    plugin: dump
    organize:
      "overlays/sbin/*": sbin/
      "overlays/templates/*": templates/

  hooks:
    source: .
    build-attributes: [enable-patchelf]
    plugin: python
    build-packages:
      - git
      - python3-setuptools
    python-requirements: [requirements.txt]
    stage-packages:
      - libpython3.10-stdlib
      - libpython3.10-minimal
      - python3-venv
      - python3.10-minimal
    override-build: |
      craftctl default
      snap-helpers write-hooks

  logrotate:
    plugin: nil
    build-attributes: [enable-patchelf]
    stage-packages:
      - logrotate
      - procps  # `pkill`
      - bzip2

  munge:
    plugin: autotools
    source: https://github.com/dun/munge.git
    source-type: git
    source-tag: munge-0.5.16
    build-attributes: [enable-patchelf]
    build-packages:
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
    stage-packages:
      - libssl3
      - zlib1g
      - libbz2-1.0
    autotools-configure-parameters:
      - --prefix=/
      - --with-munge-socket=/var/snap/${SNAPCRAFT_PROJECT_NAME}/common/run/munge/munged.socket.2
      - --with-crypto-lib=openssl

  mungectl:
    source: src/mungectl
    plugin: go
    build-snaps:
      - go/1.22/stable

  slurm:
    plugin: nil
    after: [munge, patch]
    # yamllint disable-line rule:line-length
    source: "https://download.schedmd.com/slurm/slurm-${SNAPCRAFT_PROJECT_VERSION}.tar.bz2"
    source-type: tar
    build-attributes: [enable-patchelf]
    build-packages:
      - libncurses-dev
      - libgtk2.0-dev
      - default-libmysqlclient-dev
      - libpam0g-dev
      - libperl-dev
      - liblua5.4-dev
      - libhwloc-dev
      - librrd-dev
      - libipmimonitoring-dev
      - hdf5-helpers
      - libfreeipmi-dev
      - libhdf5-dev
      - man2html
      - libcurl4-openssl-dev
      - libpmix-dev
      - libhttp-parser-dev
      - libyaml-dev
      - libjson-c-dev
      - libjwt-dev
      - liblz4-dev
      - libdbus-1-dev
      - librdkafka-dev
      - librocm-smi-dev
      - libibmad-dev
      - libibumad-dev
      - libnuma-dev
      - libaec-dev
    stage-packages:
      - libncurses5
      - libgtk2.0-0
      - libmysqlclient21
      - libpam0g
      - libperl5.34
      - liblua5.4-0
      - libhwloc15
      - librrd8
      - libipmimonitoring6
      - libfreeipmi17
      - hdf5-helpers
      - man2html
      - libcurl4
      - libpmix2
      - libhttp-parser2.9
      - libyaml-0-2
      - libjson-c5
      - libjwt0
      - liblz4-1
      - libdbus-1-3
      - librdkafka1
      - librocm-smi64-1
      - libibmad5
      - libibumad3
      - libnuma1
      - libaec0
      - libsz2
      - libhdf5-hl-100
      - libhdf5-103-1
      - util-linux  # `setpriv`
    override-build: |
      craftctl default

      set -e
      # Apply patches to Slurm.
      for patch in ${CRAFT_STAGE}/patches/slurm/*.patch; do
        echo "Applying $(basename "$patch") ..."
        patch \
          --batch \
          --forward \
          --strip 1 \
          --input "$patch"
      done
      echo "Remaking all Makefile.in for Slurm ..."
      automake

      # Compile Slurm with custom patches applied.
      ./configure \
        --prefix=${CRAFT_PART_INSTALL} \
        --disable-developer \
        --disable-debug \
        --enable-slurmrestd \
        --enable-multiple-slurmd \
        --with-munge=${CRAFT_STAGE} \
        --with-libcurl \
        --with-http-parser \
        --with-yaml \
        --with-json \
        --with-jwt \
        --with-hdf5=yes \
        --with-rdkafka \
        --with-freeipmi \
        --with-ofed \
        --with-pmix
      make -j${CRAFT_PARALLEL_BUILD_COUNT} && make install

  slurm-prometheus-exporter:
    after: [slurm]
    source: "https://github.com/rivosinc/prometheus-slurm-exporter.git"
    source-tag: "v1.4.1"
    plugin: go
    build-environment:
      - CPATH: ${CRAFT_STAGE}/include
    build-packages:
      - swig
    build-snaps:
      - go/1.22/stable
