#!/bin/sh -e
# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details

# Set up snap specific directories and configuration.
mkdir -m 0711 "${SNAP_DATA}/etc"
mkdir -p "${SNAP_DATA}/etc/default"
mkdir -p "${SNAP_DATA}/var/lib"
mkdir -p "${SNAP_DATA}/var/log"
mkdir -p "${SNAP_DATA}/var/run"
mkdir -p "${SNAP_DATA}/var/spool"
echo "MUNGE_NUM_THREADS=1" >> "${SNAP_DATA}/etc/default/slurm-snap"
echo "SLURMD_CONF_SERVER=" >> "${SNAP_DATA}/etc/default/slurm-snap"

# Set up munge-specific directories and munge key.
mkdir -m 0700 "${SNAP_DATA}/etc/munge"
mkdir -m 0711 "${SNAP_DATA}/var/lib/munge"
mkdir -m 0755 "${SNAP_DATA}/var/run/munge"
"${SNAP}"/usr/sbin/mungekey -c -k "${SNAP_DATA}/etc/munge/munge.key"

# Set up slurm-specific directories.
mkdir -m 0755 "${SNAP_DATA}/etc/slurm"
mkdir "${SNAP_DATA}/etc/slurm/plugstack.conf.d"
mkdir "${SNAP_DATA}/etc/slurm/epilog.d/"
mkdir "${SNAP_DATA}/etc/slurm/prolog.d/"
mkdir "${SNAP_DATA}/var/log/slurm"
mkdir "${SNAP_DATA}/var/spool/slurmd"
mkdir "${SNAP_DATA}/var/lib/slurmd"
touch "${SNAP_DATA}/var/lib/slurmd/node_state"
touch "${SNAP_DATA}/var/lib/slurmd/front_end_state"
touch "${SNAP_DATA}/var/lib/slurmd/job_state"
touch "${SNAP_DATA}/var/lib/slurmd/resv_state"
touch "${SNAP_DATA}/var/lib/slurmd/trigger_state"
touch "${SNAP_DATA}/var/lib/slurmd/assoc_mgr_state"
touch "${SNAP_DATA}/var/lib/slurmd/assoc_usage"
touch "${SNAP_DATA}/var/lib/slurmd/qos_usage"
touch "${SNAP_DATA}/var/lib/slurmd/fed_mgr_state"
# Make it so slurm libraries can be found by applications that use the SLURM APIs.
ldconfig -n "$(dirname "${SNAP}")/current/lib/slurm"
